import { COLOR_TYPES } from "./types";

const COLORS = {
	WHITE: COLOR_TYPES.WHITE,
	BLACK: COLOR_TYPES.BLACK,
	PRIMARY: COLOR_TYPES.PRIMARY,
	SECONDARY: COLOR_TYPES.SECONDARY,
	INACTIVE: COLOR_TYPES.INACTIVE,
	DARK: COLOR_TYPES.DARK,
	GRAY: COLOR_TYPES.GRAY,
};

export default COLORS;
