import { COLOR_TYPES } from "./types";

const COLORS = {
	WHITE: COLOR_TYPES.WHITE,
	BLACK: COLOR_TYPES.BLACK,
	MAIN: COLOR_TYPES.MAIN,
	INACTIVE: COLOR_TYPES.INACTIVE,
	DARK: COLOR_TYPES.DARK,
	GRAY: COLOR_TYPES.GRAY,
};

export default COLORS;
